### ISSUE TITLE
Map covers over modal when attempting to delete resource

### ISSUE THREAD

**Issue by clarkewing** [davidpiesse/nova-map#1]
The z-index of the map container needs to be set to a value such as 1. Otherwise, when attempting to delete a resource, the confirmation modal is covered by the map (see screenshot).
<img width="1404" alt="screen shot 2018-09-02 at 16 47 58" src="https://user-images.githubusercontent.com/7689302/44957226-1e533400-aed0-11e8-988f-76b4fd9318f1.png">

**Comment by davidpiesse** [comment]
Good catch! I'm guessing the z index needs to be more explicitly set. Do you know the z index of your modal?

**Comment by davidpiesse** [comment]
Fixed this in v 0.0.2
Thanks man :)
