### ISSUE TITLE
Save Polygon in MySQL Table

### ISSUE THREAD

**Issue by stezani** [davidpiesse/nova-map#13]
Hi! Thank you for this plugin. Can i save my polygons that i drew when i'm creating a resource? Thank you.

**Comment by dakira** [comment]
@davidpiesse any progress on implementing editing?

**Comment by davidpiesse** [comment]
Hi Matthias,

At the moment no.
Much of the original implementation code is still in there but I have not
had the time to dedicate to getting it fully working.
I am happy to accept PR's that add this :)

David

**Comment by dakira** [comment]
Great, I'll have a look!
