### ISSUE TITLE
Avoid Map Drag

### ISSUE THREAD

**Issue by Yelles** [davidpiesse/nova-map#14]
Hi,
Thanks for your work.
Is there a way to disable the drag ?

**Comment by alcis-dev** [comment]
It is a Leaflet thing...
```js
map.dragging.disable();
```
https://leafletjs.com/reference-1.4.0.html#map-dragging

This would be a custom bit of code to override this.

**Comment by Yelles** [comment]
> It is a Leaflet thing...
> 
> ```js
> map.dragging.disable();
> ```
> 
> https://leafletjs.com/reference-1.4.0.html#map-dragging
> 
> This would be a custom bit of code to override this.

thank you for pointing me that;)
