### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Enmaboya** [davidpiesse/nova-map#2]
hi!
I added a field to my resource
             Map :: make ('Some Point Field', 'coordinates')
                 -> spatialType ('Point'),

but nothing is displayed.
my coordinates are written like this:
54.303910, 48.301921.

what could be wrong?

![default](https://user-images.githubusercontent.com/32259003/45686222-e3eac780-bb5c-11e8-9319-b701eba7a561.png)

**Comment by davidpiesse** [comment]
I have added a new spatial type 'LatLonField'
```php
Map::make('Field Title', 'coordinates')
     ->spatialType('LatLonField')
```
It is also documented in the readme 😄 

Thanks again
