### ISSUE TITLE
Use Declaration

### ISSUE THREAD

**Issue by packytagliaferro** [davidpiesse/nova-map#3]
What Use declaration do I need to have to import?

I tried 

```
use Davidpiesse\Map;
use Map;

```
Both give an error `Class not found`

**Comment by packytagliaferro** [comment]
Never mind. I noticed the namespace is map so `use Davidpiesse\Map\Map;` worked

**Comment by davidpiesse** [comment]
Just about to type that in!
Glad you got it working 🍬

**Comment by simtrax** [comment]
Do you want a PR that tells users how to use the package? 
I ended up here as well.

**Comment by davidpiesse** [comment]
Would certainly be appreciated :)
