### ISSUE TITLE
Point is not displayed

### ISSUE THREAD

**Issue by AGNICO** [davidpiesse/nova-map#7]
Hi, I have problem  to display map point. I used default example from LaravelMysqlSpacial:

```
$place1->name = 'Empire State Building';
$place1->point = new Point(40.7484404, -73.9878441);
```

but if I use in Nova:

```
Map::make('Position', 'Empire State Building')
            ->spatialType('Point')
```

The map points somewhere to the middle of Atlantic ocean and point is not displayed.

'point' column in DB has value : 000000000101000000FBC275D6387F52C0A98020E5CC5F4440

**Comment by davidpiesse** [comment]
Hi @AGNICO ,
It is likely if your point is in the Atlantic it is at 0,0 (off the west coast of Africa).
This could mean a few things:
* The data never saved correctly to the DB (unlikely)
* Using LaravelMysqlSpatial does something different to grimzy's package (possible)
*  The code you posted above isn't quite right (likely)

The code for a Map field should be
```php
Map::make('Some Polygon Field', 'polygon_field_name')
    ->spatialType('Polygon'),
```
I think your 'Empire State Building' field should refer to a DB column / model property.

Let me know what you find out :)

**Comment by AGNICO** [comment]
My Model.php
```
protected $spatialFields = [
        'geometry',
        'point',
        'line_string',
        'polygon',
        'multi_point',
        'multi_line_string',
        'multi_polygon',
        'geometry_collection'
    ];
```
My Nova/Model.php

```
Map::make('Position', 'point')
            ->spatialType('Point')
            ->height('300px'),
```
My Place.php model:
```
protected $spatialFields = [
        'geometry',
        'point',
        'line_string',
        'polygon',
        'multi_point',
        'multi_line_string',
        'multi_polygon',
        'geometry_collection'
    ];
```

My DB record (table places):
id: 1
name: point
geometry: null
point: 000000000101000000FBC275D6387F52C0A98020E5CC5F4440
line_string: null
other columns also null, only point column is not empty

The map still points to the Atlantic

**Comment by davidpiesse** [comment]
Hi!

Are you using the Spatial trait from Grimzy?
https://github.com/grimzy/laravel-mysql-spatial

such as 
```php
class Place extends Model
{
    use SpatialTrait;

    protected $spatialFields = [
        'geometry',
        'point'
    ];
}
```

**Comment by AGNICO** [comment]
yes, of course

**Comment by davidpiesse** [comment]
Any errors in the console on the front end in Nova?
Any way you can confirm it is at Null Island?
https://en.wikipedia.org/wiki/Null_Island

**Comment by AGNICO** [comment]
No errors in console.

Yes, the map is centered at Null Island, but the point icon is missing.

**Comment by davidpiesse** [comment]
OK;
The default center is [0,0].

If no error is being called then it must be running  ``` this.setCenter()``` once mounted.

Which means this is where the error/issue starts and the geojson prop is null.
```
if(this.geojson !== null){
    ...
}
```
this means that the value being passed to the map is null or is being left as the default (which is null)
```
return this.value
```
The value is set by
```
<map-detail 
    :type="field.spatialType" 
    :value="field.value"
```

Could you confirm that null is being sent to the page? It is contained within a XHR call /1 (the id of the record) and look into the field resource {resource->fields[x]->value}

I can't see where is it obviously going awry - so hoping to get a bit of insight :)

**Comment by AGNICO** [comment]
Yes, resource->fields[:id]->value is null

**Comment by AGNICO** [comment]
Also namespace for Model.php is not App\Model.php, but App\Models\Model.php, but I don't think this is an issue.

Anyway, nice package, thank you for your effort, hope we can solve this.

**Comment by AGNICO** [comment]
Nova resource does not have any SpatialTrait. Only 'Model.php' and Place.php have.
