### ISSUE TITLE
Is there a plan to make a search by point and radius?

### ISSUE THREAD

**Issue by eboye** [davidpiesse/nova-map#8]
I'm struggling to find an approach to implement an map interfere to search for users within a circle on a map.

I know it's not a field, but maybe you guys have an idea what could be used to filter users by latlng and do an nova action on them?

**Comment by alcis-dev** [comment]
There is no plan to implement search at this time. 
However a PR will be happily accepted with the functionality in it for an action/search/filter etc.

Filtering is possible spatially, but it depends on the format of the incoming spatial data.
If it is true db spatial (MySQL Spatial types) then we can use DB functions to do buffers and within.
For GeoJSON and LatLon fields we need to manually implement this.

We would also need to allow for polygons and polylines as well and overlaps/contains filters as well.
All is possible but its a branch of the original intention of this project.

N.B. I would have added this functionality to a separate package before for a opportunity I had but it never materialized.

D

**Comment by eboye** [comment]
Thanks for a response ... I think I know now how I'll approach. I'll sure make a PR if I make any changes that will benefit the library 😉

**Comment by davidpiesse** [comment]
There is no plan to implement search at this time.
However a PR will be happily accepted with the functionality in it for an action/search/filter etc.

Filtering is possible spatially, but it depends on the format of the incoming spatial data.
If it is true db spatial (MySQL Spatial types) then we can use DB functions to do buffers and within.
For GeoJSON and LatLon fields we need to manually implement this.

We would also need to allow for polygons and polylines as well and overlaps/contains filters as well.
All is possible but its a branch of the original intention of this project.

N.B. I would have added this functionality to a separate package before for a opportunity I had but it never materialized.

D
