### ISSUE TITLE
Instalation problems

### ISSUE THREAD

**Issue by IgorBondarenk** [davidpiesse/nova-map#9]
Can you give me a detailed guide about the installation of your package? I executed "php artisan nova:field davidpiesse/nova-map", after that I haven't Map class in my nova resource class.

**Comment by davidpiesse** [comment]
Hi @IgorBondarenk ,

The use of nova:field is for your own custom fields and not external ones.

Instructions for the installation of this plugin can be found here
https://novapackages.com/packages/davidpiesse/nova-map
